version: "3"

networks:
    network_1:
services:
    cgy:
      image: "registry.cn-hangzhou.aliyuncs.com/banff/cgy-client:latest"
      networks:
        - network_1
      ports:
        - 81:80
      depends_on:
        - ofbiz
      logging:
        driver: "json-file"
        options:
          max-size: "20m"
    gh:
      image: "registry.cn-hangzhou.aliyuncs.com/banff/union:latest"
      networks:
        - network_1
      ports:
        - 82:80
      depends_on:
        - ofbiz
      logging:
        driver: "json-file"
        options:
          max-size: "20m"
    ofbiz:
      image: "registry.cn-hangzhou.aliyuncs.com/banff/tradeunion:latest"
      networks:
        - network_1
      ports:
        - 8081:8081
      volumes:
        - "/opt/cgy_gh/tradeunion/tu_volume/config/entityengine.xml:/root/ofbiz/framework/entity/config/entityengine.xml"
        - "/opt/cgy_gh/tradeunion/tu_volume/logs:/root/ofbiz/runtime/logs"
        - "/opt/cgy_gh/tradeunion/tu_volume/config/ofbiz-component.xml:/root/ofbiz/framework/catalina/ofbiz-component.xml"
        - "/opt/cgy_gh/tradeunion/tu_volume/config/url.properties:/root/ofbiz/framework/webapp/config/url.properties"
        - "/opt/cgy_gh/tradeunion/tu_volume/config/log4j2.xml:/root/ofbiz/framework/base/config/log4j2.xml"
        - "/opt/cgy_gh/tradeunion/tu_volume/config/security.properties:/root/ofbiz/framework/security/config/security.properties"
        - "/opt/cgy_gh/tradeunion/tu_volume/.gradle:/root/.gradle"
      logging:
        driver: "json-file"
        options:
          max-size: "20m"
